import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';

import Intro from './components/Intro';
import Experience from './components/Experience';
import Projects from './components/Projects';

import { useState } from 'react';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Edward Jin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white dark:bg-black px-10 md:px-20 lg:px-40">
        <Intro darkMode={darkMode} setDarkMode={setDarkMode} />

        <Experience />
        
        <Projects />
        
      </main>
      <footer className="w-100 text-center p-4 bg-white rounded-lg shadow dark:bg-black dark:rounded-none">
          <span className="text-sm text-gray-500 dark:text-gray-400">
            © 2024 Edward Jin. All Rights Reserved.
          </span>
      </footer>
    </div>
  )
}
